export {
  buscarCategoriasPromocaoAdminSchema,
  buscarFretesServicosPromocaoAdminSchema,
  buscarMarcasPromocaoAdminSchema,
  buscarProdutosPromocaoAdminSchema,
  buscarRegioesPromocaoAdminSchema,
  cupomPromocaoCalculavelSchema,
  entradaCalculoPromocoesSchema,
  filtrosAuditoriaCuponsAdminSchema,
  filtrosCuponsPromocaoAdminSchema,
  filtrosExportacaoAuditoriaCuponsAdminSchema,
  filtrosPromocoesAdminSchema,
  idPromocaoAdminSchema,
  itemEntradaPromocaoSchema,
  marcarLegadoRelampagoMigradoAdminSchema,
  regraFreteGratisPromocaoCalculavelSchema,
  regraSubtotalPromocaoCalculavelSchema,
  regraPromocaoCalculavelSchema,
  salvarPromocaoAdminSchema,
  salvarCupomPromocaoAdminSchema,
  statusPromocaoSchema,
  tipoBeneficioPromocaoSchema,
  tipoCampanhaPromocaoSchema,
  tipoDescontoPromocaoSchema,
  vinculoCategoriaPromocaoCalculavelSchema,
  vinculoMarcaPromocaoCalculavelSchema,
  vinculoProdutoPromocaoCalculavelSchema,
} from "./promocao.schema";
