export type {
  ContextoCalculoPromocao,
  CupomPromocaoCalculavel,
  EscopoPromocaoAplicada,
  EntradaCalculoPromocoes,
  ItemEntradaPromocao,
  ItemPromocaoCalculado,
  PromocaoAplicada,
  RegraFreteGratisPromocaoCalculavel,
  RegraPromocaoCalculavel,
  RegraSubtotalPromocaoCalculavel,
  ResultadoCalculoPromocoes,
  StatusPromocao,
  TipoCampanhaPromocao,
  TipoBeneficioPromocao,
  TipoDescontoPromocao,
  VinculoCategoriaPromocaoCalculavel,
  VinculoMarcaPromocaoCalculavel,
  VinculoProdutoPromocaoCalculavel,
} from "./promocoes.types";
export {
  statusPromocao,
  tiposBeneficioPromocao,
  tiposCampanhaPromocao,
  tiposDescontoPromocao,
} from "./promocoes.types";
export type {
  CategoriaPromocaoAdmin,
  CupomPromocaoAdmin,
  FreteGratisPromocaoAdmin,
  FreteServicoPromocaoAdmin,
  InconsistenciaAuditoriaCupomAdmin,
  ItemDiagnosticoOfertaRelampagoAdmin,
  ItemEstabilidadeMigracaoRelampagoAdmin,
  MarcaPromocaoAdmin,
  OrigemDiagnosticoOfertaRelampago,
  PedidoAuditoriaFreteGratisAdmin,
  ProdutoPromocaoAdmin,
  PromocaoAdmin,
  RegiaoPromocaoAdmin,
  ResultadoAuditoriaCuponsAdmin,
  ResultadoAuditoriaFreteGratisAdmin,
  ResultadoCuponsPromocaoAdmin,
  ResultadoDiagnosticoOfertasRelampagoAdmin,
  ResultadoEstabilidadeMigracaoRelampagoAdmin,
  ResultadoPromocoesAdmin,
  ResumoAuditoriaCuponsAdmin,
  ResumoAuditoriaFreteGratisAdmin,
  ResumoDiagnosticoOfertaRelampagoAdmin,
  ResumoEstabilidadeMigracaoRelampagoAdmin,
  StatusDiagnosticoOfertaRelampago,
  StatusEstabilidadeMigracaoRelampago,
  StatusPagamentoAuditoriaCupom,
  SubtotalPromocaoAdmin,
  UsoCupomAuditoriaAdmin,
} from "./promocoes-admin.types";
export type {
  CampanhaPromocionalLegadaAdaptada,
  CountdownPromocionalLegadoAdaptado,
  OpcoesAdaptacaoPromocoesLegadas,
  PromocaoLegadaEntrada,
  ResultadoAdaptacaoPromocoesLegadas,
  TipoBadgePromocionalLegado,
  TipoCampanhaPromocionalLegada,
  TipoPromocaoLegada,
} from "./promocoes-legadas.types";
